# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: '/etc/wazo-upgrade/conf.d'

auth:
  host: localhost
  port: 9497
  verify_certificate: /usr/share/xivo-certs/server.crt

plugind:
  host: localhost
  port: 9503
  verify_certificate: /usr/share/xivo-certs/server.crt
